import "@/styles/globals.css";

import { Be_Vietnam_Pro as FontSans } from "next/font/google";
import { type Metadata } from "next";

import { cn } from "@/lib/utils";
import { Header } from "@/components/layout/header";

export const metadata: Metadata = {
  title: "Unsplash Box",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["300", "500", "600"],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={cn(
        "bg-background font-sans font-light antialiased",
        fontSans.variable,
      )}
    >
      <body className="flex min-h-screen flex-col">
        <Header />
        <main className="flex flex-1">{children}</main>
        <footer className="z-10 px-4 text-center 2xl:text-left">
          <div className="mx-auto max-w-lg py-8">
            Made by <span className="font-semibold">@mattwelson</span>
          </div>
        </footer>
      </body>
    </html>
  );
}
