import "@/styles/globals.css";

import { Be_Vietnam_Pro as FontSans } from "next/font/google";
import { type Metadata } from "next";

import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Unsplash Box",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["300", "500", "600"],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={cn(
        "bg-background min-h-screen font-sans font-medium antialiased",
        fontSans.variable,
      )}
    >
      <body>{children}</body>
    </html>
  );
}
